# Generated by Django 5.0.6 on 2024-06-19 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_producto',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_categoria', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cli', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cli', models.CharField(max_length=70)),
                ('email_cli', models.EmailField(max_length=80)),
                ('pass_cli', models.CharField(max_length=30)),
                ('direccion_cli', models.CharField(max_length=200)),
                ('telefono_cli', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_carro',
            fields=[
                ('id_detalle_carro', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_prod', models.IntegerField()),
                ('precio_prod', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto_pago', models.IntegerField()),
                ('fecha_pago', models.DateField()),
                ('referencia_trans_pago', models.CharField(max_length=20)),
                ('estado_pago', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Carro_compra',
            fields=[
                ('id_carro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_crea_carro', models.DateField()),
                ('total_monto_carro', models.IntegerField()),
                ('id_cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cliente')),
                ('id_detalle_carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.detalle_carro')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_orden', models.DateField()),
                ('total_orden', models.IntegerField()),
                ('estado_orden', models.CharField(max_length=10)),
                ('id_cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cliente')),
                ('id_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pago')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('descri_producto', models.CharField(max_length=150)),
                ('precio_producto', models.IntegerField()),
                ('estado_producto', models.BooleanField(default=True)),
                ('img_producto', models.ImageField(upload_to='')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categoria_producto')),
            ],
        ),
        migrations.AddField(
            model_name='detalle_carro',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.producto'),
        ),
    ]
