# Generated by Django 5.0.6 on 2024-06-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descri_producto',
            field=models.TextField(max_length=150),
        ),
    ]
