# Generated by Django 5.0.6 on 2024-06-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_producto_img_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='img_producto',
            field=models.ImageField(upload_to='productos'),
        ),
    ]
