# Generated by Django 5.0.6 on 2024-06-20 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_producto_img_producto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalle_carro',
            options={'verbose_name': 'Detalle_carro'},
        ),
        migrations.AlterModelOptions(
            name='orden',
            options={'verbose_name': 'Orden', 'verbose_name_plural': 'Ordenes'},
        ),
        migrations.AlterField(
            model_name='producto',
            name='descri_producto',
            field=models.TextField(max_length=150, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado_producto',
            field=models.BooleanField(default=True, verbose_name='Disponibilidad'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categoria_producto', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_producto',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_producto',
            field=models.IntegerField(verbose_name='Precio'),
        ),
    ]
