# Generated by Django 5.0.6 on 2024-06-27 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_producto_img_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro_compra',
            name='fecha_crea_carro',
        ),
        migrations.RemoveField(
            model_name='carro_compra',
            name='id_detalle_carro',
        ),
        migrations.RemoveField(
            model_name='carro_compra',
            name='total_monto_carro',
        ),
        migrations.RemoveField(
            model_name='detalle_carro',
            name='precio_prod',
        ),
        migrations.AddField(
            model_name='detalle_carro',
            name='id_carro',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.CASCADE, to='main.carro_compra'),
            preserve_default=False,
        ),
    ]
