# Generated by Django 5.0.6 on 2024-06-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_carro_compra_id_cli_carro_compra_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_carro',
            name='cantidad_prod',
            field=models.IntegerField(default=1),
        ),
    ]
