# Generated by Django 5.0.6 on 2024-07-17 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_detalle_carro_cantidad_prod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='id_cli',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='id_pago',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Orden',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
